
package vista;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


public class PanelFondo extends javax.swing.JPanel {

    private final Dimension tamanio;
    
    public PanelFondo() {
        initComponents();
        //resolucion de la imagen
        this.setSize(1181,827);
        //tamaño de la pantalla
        tamanio = Toolkit.getDefaultToolkit().getScreenSize();
        //centramos la imagen cogiendo el ancho y el largo de la pantalla y devidiendolo por 2
        this.setLocation((tamanio.width/2)-(this.getWidth()/2), (tamanio.height/2)-(this.getHeight()/2));
    }
/**
 * Insertamos la imgen especificando su ruta 
 * @param g grafico
 */    
    @Override
    public void paintComponent(Graphics g){
         Dimension tamanio = getSize();
         ImageIcon imagenFondo = new ImageIcon(getClass().getResource("images/udaleku-15-02.png"));
         g.drawImage(imagenFondo.getImage(),0,0,tamanio.width,tamanio.height,null);
         setOpaque(false);
         super.paintComponent(g);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
