
package vista;

import Excepciones.CampoVacio;
import Excepciones.DniNoValido;
import Excepciones.FechaNoValida;
import Excepciones.TelefonoNoValido;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import udalekuak.Control;
import uml.CentroEd;
import uml.Inscripcion;
import uml.Solicitud;
import uml.Tutor;

/**
 *
 * @author javi&Jon 
 */
public class Sinscripcion extends javax.swing.JDialog {

    private umldirecciones.Direccion direccion;
    private int contador;
    private Inscripcion inscrip;
    private Solicitud sol;
    private CentroEd centro;
    private String telf1; 
    private String telf2; 
    private String telf3; 
    private String telf4; 
    
    /**
     * Creates new form Sinscripcion
     * 
     * crea una nueva solicitud en la variable 
     * pone el contador a 1 
     */
    public Sinscripcion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Solicitud de inscripción");
        contador = 1;
        sol = Control.creaSolicitud();
        //deshabilitarTelefonos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgsexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNombreT = new javax.swing.JTextField();
        tfApelpT = new javax.swing.JTextField();
        tfApelsT = new javax.swing.JTextField();
        bDireccion = new javax.swing.JButton();
        chbTelf1 = new java.awt.Checkbox();
        chbTelf2 = new java.awt.Checkbox();
        chbTelf3 = new java.awt.Checkbox();
        chbTelf4 = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDireccion = new javax.swing.JTextArea();
        ftfDniT = new javax.swing.JFormattedTextField();
        tfTelf1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfTelf2 = new javax.swing.JTextField();
        tfTelf3 = new javax.swing.JTextField();
        tfTelf4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNombreM = new javax.swing.JTextField();
        tfApelpM = new javax.swing.JTextField();
        tfApelsM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        chbDiscapacidad = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        cbCentro = new javax.swing.JComboBox();
        ftfFechaNac = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftfModelo = new javax.swing.JFormattedTextField();
        ftfDniM = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        blimpiar = new javax.swing.JButton();
        bParticipante = new javax.swing.JButton();
        bFinalizar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel1.setText("Solicitud de Inscripción");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Datos del padre/madre o tutor");

        jLabel3.setText("DNI");

        jLabel4.setText("nombre");

        jLabel5.setText("primer apellido");

        jLabel6.setText("segundo apellido");

        bDireccion.setText("Direccón");
        bDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDireccionActionPerformed(evt);
            }
        });

        taDireccion.setColumns(20);
        taDireccion.setRows(5);
        jScrollPane1.setViewportView(taDireccion);

        try {
            ftfDniT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setText("Telefonos:");

        jLabel18.setText("importante: indica en la casilla cual es el telefono de localización en caso de urgencia.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(bDireccion))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApelpT)
                            .addComponent(tfNombreT)
                            .addComponent(ftfDniT)
                            .addComponent(tfApelsT)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(29, 29, 29)
                                .addComponent(tfTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelf3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTelf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelf4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTelf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(ftfDniT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApelpT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfApelsT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bDireccion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(tfTelf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbTelf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbTelf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbTelf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbTelf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 2, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Datos del menor");

        jLabel8.setText("DNI");

        jLabel9.setText("nombre");

        jLabel10.setText("primer apellido");

        jLabel11.setText("Segundo apellido");

        jLabel12.setText("sexo");

        bgsexo.add(rbHombre);
        rbHombre.setText("Hombre");

        bgsexo.add(rbMujer);
        rbMujer.setText("Mujer");

        jLabel13.setText("Fecha de nacimiento");

        chbDiscapacidad.setText("Discapacidad");

        jLabel14.setText("Centro de ensañanza");

        cbCentro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ftfFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel15.setText("Modelo");

        try {
            ftfModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfDniM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("(A-B-C)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(chbDiscapacidad)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel12)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreM)
                            .addComponent(tfApelpM)
                            .addComponent(tfApelsM)
                            .addComponent(cbCentro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftfDniM)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbHombre)
                                        .addGap(38, 38, 38)
                                        .addComponent(rbMujer))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ftfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addComponent(ftfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfDniM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfApelpM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApelsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ftfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbDiscapacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ftfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        blimpiar.setText("Limpiar Datos");
        blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarActionPerformed(evt);
            }
        });

        bParticipante.setText("Añadir participante");
        bParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParticipanteActionPerformed(evt);
            }
        });

        bFinalizar.setText("Finalizar Iscripcion");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        bCancelar.setText("Salir sin guardar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(255, Short.MAX_VALUE)
                        .addComponent(bParticipante)
                        .addGap(18, 18, 18)
                        .addComponent(bFinalizar)
                        .addGap(52, 52, 52)
                        .addComponent(bCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(blimpiar))
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFinalizar)
                    .addComponent(bParticipante)
                    .addComponent(bCancelar))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Cierra el dialogo de inscripción
 * @param evt  */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        ControlVistas.cerrarDialogo(this);
    }//GEN-LAST:event_bCancelarActionPerformed

/**
 * Consulta de dirección en la Base de Datos
 * @param evt 
 */
    private void bDireccionActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //direccion = controldirecciones.Control.creaDireccion();
        direccion = controldirecciones.Control.eligeDireccion(this, true, direccion);
         //Esta linea es para comprobar el objeto direccion que devuelve
        javax.swing.JOptionPane.showMessageDialog(this, direccion.toString());       
    }                                          


/**
 * Se añade un nuevo participante a la solictud
 * @param evt 
 */
    private void bParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParticipanteActionPerformed
        //guarda la inscripcion
        guardaDatosInscripcion();
        //Pregunta si queremos conservar los datos de tutor
        limpiar();    
        //comprueba cuantas inscripciones hay ya en la solicitud
        //cuando hay dos inscripciones deshabilita el boton anadir participante
        compruebaCantidadInscripciones();    
        
              
        
            
    }//GEN-LAST:event_bParticipanteActionPerformed
    /**
     * Guarda los datos en un objeto inscripcion para poder pasar a la siguiente si la hubiese
     */
    private void guardaDatosInscripcion()
    {
        //valida los datos del formulario 
        if(validaDatos())
        {   
            //Si es correcto procede a guardar datos
            //crea inscripcion
            inscrip = Control.creaInscripcion();
            //anade id inscripcion
            inscrip.setIdIns(contador);
            contador ++;
            //anade solicitud a inscripcion, y ademas anade inscripcion en solicitud.inscripciones(arrayList)
            inscrip.setSolicitudBidireccional(sol);
            //anade direccion
            inscrip.setDireccion(direccion);
            //si tutor no existe
            Tutor t = Control.buscaTutor(this.ftfDniT.toString());
            if(t==null)
            {
                //anade tutor pasandole los datos del formulario
                inscrip.setTutor(
                        this.ftfDniT.getText(),
                        this.tfNombreT.getText(),
                        this.tfApelpT.getText(),
                        this.tfApelsT.getText()
                );
            //si tutor existe
            }else
            {
                //anade el tutor buscado anteriormente
                inscrip.setTutor(t);
            }
            
            //averigua el sexo
            char sexo;
            if(rbHombre.isSelected())
                sexo = 'H';
            else
                sexo = 'M';
            //gurada los datos anadiendo un menor a la inscripcion
            inscrip.setMenor(
                    this.ftfDniM.getText(),
                    this.tfNombreM.getText(),
                    this.tfApelpM.getText(),
                    this.tfApelsM.getText(),
                    sexo,
                    this.ftfFechaNac.getText(),
                    this.chbDiscapacidad.isSelected(),
                    this.ftfModelo.getText().charAt(0),
                    centro                
            );
            //anade los telefonos
            inscrip.setTelf1(tfTelf1.getText());
            inscrip.setTelf2(tfTelf2.getText());
            inscrip.setTelf3(tfTelf3.getText());
            inscrip.setTelf4(tfTelf4.getText());
            
            //anade anadir telefono de contacto
            
            //inscripcion ya esta completa
        }
        
        //se comprueba si el menor ya esta inscrito en otra solicitud de la BD
        //NOTA!! falta comprobar si esta repetido en la solicitud en curso
        if(Control.existeMenor(inscrip.getMenor()))
        {
            //si que lo esta
            //mensaje de error
            JOptionPane.showMessageDialog
            (
                this, 
                inscrip.getMenor().getNombre() +
                " " +
                inscrip.getMenor().getApel1() +
                " " +
                inscrip.getMenor().getApel2() +
                " ya esta inscrito en otra solicitud.\n" +
                "¡NO PUEDE APUNTAR DOS VECES A LA MISMA PERSONA!"
            );            
            //se borran los datos de menor          
            this.limpiarMenor();
        }
        //si no esta repetido se continua con el proceso
    }  
 /**
 * Finaliza la Solicitud
 * @param evt 
 */
    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        //guarda la inscripcion
        guardaDatosInscripcion();
        try
        {
            //he quitado el parametro que pasaba esta ventana como padre
            //al cambiarse la forma de llamar a las ventanas desde control vista ya no hace falta
           udalekuak.Control.finalizarSolicitud(sol);
        }
        catch (Exception e) {
            ControlVistas.enviarMensaje("Fallo al guardar la solicitud");
        }
    }//GEN-LAST:event_bFinalizarActionPerformed
/**
 * limpia todos los campos de la ventana
 * @param evt 
 */
    private void blimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarActionPerformed
        limpiarTutor();
        limpiarMenor();
    }//GEN-LAST:event_blimpiarActionPerformed

//GEN-FIRST:event_bDireccionActionPerformed
 
//GEN-LAST:event_bDireccionActionPerformed

/**
 * Se pide confirmación para conservar los datos del tutor
 * o borrarlos
 * @return 
 */
    private void limpiar(){
       int conf = JOptionPane.showConfirmDialog(null, "Desea conservar los datos de tutor");
       if(conf==0)
           limpiarMenor();
       if(conf==1){
           limpiarMenor();
           limpiarTutor();
       }
    }

/**
 * Se limpian los campos del panel de menor
 */  
    private void limpiarMenor(){
        tfNombreM.setText(null);
        tfApelpM.setText(null);
        tfApelsM.setText(null);
        ftfDniM.setText(null);
        ftfFechaNac.setText(null);
        contador--;            
        centro = null;
        inscrip = null;
    }
/**
 * Se limpian los campos del panel de tutor
 */    
    private void limpiarTutor(){
        tfNombreT.setText(null);
        tfApelpT.setText(null);
        tfApelsT.setText(null);
        ftfDniT.setText(null);        
    }
    
    
/**
 * Deshabilita los campos de telefono menos el primero
 * y quita el tic del checkbox
 */    
    private void deshabilitarTelefonos(){
        chbTelf1.setEnabled(true);
        chbTelf2.setEnabled(false);
        chbTelf3.setEnabled(false);
        chbTelf4.setEnabled(false);
        chbTelf1.setState(false);
        chbTelf2.setState(false);
        chbTelf3.setState(false);
        chbTelf4.setState(false);
    }
    
    /**
     * Valida los datos del formulario antes de proceder a guardar los datos
     */
    private boolean validaDatos(){
        try{
            validarDniT();
            validarDniM();
            validarString();            
            validarTelefono();
            validarSexo();
            validarFechaN();
            validarDiscapacidad();
            validarCentro();
            validarModelo();
            
            return true;
        }
        catch(CampoVacio e){
            JOptionPane.showMessageDialog(this,e.getMessage());
            return false;
        }
        catch (DniNoValido e) {
            JOptionPane.showMessageDialog(this,"El dni no es correcto");
            return false;
        }
        catch(TelefonoNoValido e){
            JOptionPane.showMessageDialog(this,"El telefono no es correcto");
            return false;
        }
        catch(FechaNoValida e){
            JOptionPane.showMessageDialog(this,"La fecha de nacimiento no es correcta");
            return false;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error en la validacion de los datos" + e.getMessage());
            return false;
        }        
    }
/**
 * Diferentes validaciones
 * @throws Exception 
 */    
    private void validarDniT() throws Exception{
        if (ftfDniT.getValue()== null)
                throw new CampoVacio("Dni");
        String juegoCaracteres="TRWAGMYFPDXBNJZSQVHLCKET";
        String dni = ftfDniT.getText().substring(0, 2);
        dni += ftfDniT.getText().substring(3, 6);
        dni += ftfDniT.getText().substring(7, 10);
        int modulo= Integer.parseInt(dni) % 23;
        char letra = juegoCaracteres.charAt(modulo);
        if (ftfDniT.getText().charAt(11)!= letra)
                throw new DniNoValido();
    }
    
    private void validarDniM() throws Exception{        
        String juegoCaracteres="TRWAGMYFPDXBNJZSQVHLCKET";
        String dni = ftfDniM.getText().substring(0, 2);
        dni += ftfDniM.getText().substring(3, 6);
        dni += ftfDniM.getText().substring(7, 10);
        int modulo= Integer.parseInt(dni) % 23;
        char letra = juegoCaracteres.charAt(modulo);
        if (ftfDniM.getText().charAt(11)!= letra)
                throw new DniNoValido();
    } 
    
    private void validarString() throws Exception{
        if (tfNombreM.getText().isEmpty())
                throw new CampoVacio("Nombre");
        if (tfNombreT.getText().isEmpty())
                throw new CampoVacio("Nombre");
        if (tfApelpT.getText().isEmpty())
                throw new CampoVacio("Apellido");
        if (tfApelsT.getText().isEmpty())
                throw new CampoVacio("Apellido");
        if (tfApelpM.getText().isEmpty())
                throw new CampoVacio("Apellido");
        if (tfApelsM.getText().isEmpty())
                throw new CampoVacio("Apellido");
        if (taDireccion.getText().isEmpty())
                throw new CampoVacio("Direccion");
        if (tfTelf1.getText().isEmpty())
                throw new CampoVacio("Telefono");
    }
    
    private void validarTelefono() throws Exception{
        Pattern pat = Pattern.compile("^[6,7,8,9]{1}[0-9]{8}$");
        Matcher mat = pat.matcher(tfTelf1.getText());
        if (mat.matches()==false) 
           throw new TelefonoNoValido();
    }
    
    private void validarSexo() throws Exception{
        if (rbHombre.isSelected() == false && rbMujer.isSelected() == false)
            throw new CampoVacio("Sexo");
    }
    
    private void validarFechaN() throws Exception{
        if (ftfFechaNac.getValue()== null)
                throw new CampoVacio("FechaN");
    }
    
    private void validarDiscapacidad() throws Exception{ 
        if (chbDiscapacidad.getIgnoreRepaint())
                throw new CampoVacio("Discapacidad");
    }
    
    private void validarCentro() throws Exception{
        if (cbCentro.getIgnoreRepaint())
                throw new CampoVacio("FechaN");
    }
    
    private void validarModelo() throws Exception{
        if (ftfModelo.getValue()== null)
                throw new CampoVacio("Modelo");
    }

/**
 * Se cuentan los participantes insertados 
 * para deshabilitar el boton de añadir otro
 */    
    private void compruebaCantidadInscripciones(){               
        if(contador==2){
          bParticipante.setEnabled(false); 
        }            
        else contador =  contador+1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sinscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sinscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sinscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sinscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sinscripcion dialog = new Sinscripcion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bDireccion;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bParticipante;
    private javax.swing.ButtonGroup bgsexo;
    private javax.swing.JButton blimpiar;
    private javax.swing.JComboBox cbCentro;
    private javax.swing.JCheckBox chbDiscapacidad;
    private java.awt.Checkbox chbTelf1;
    private java.awt.Checkbox chbTelf2;
    private java.awt.Checkbox chbTelf3;
    private java.awt.Checkbox chbTelf4;
    private javax.swing.JFormattedTextField ftfDniM;
    private javax.swing.JFormattedTextField ftfDniT;
    private javax.swing.JFormattedTextField ftfFechaNac;
    private javax.swing.JFormattedTextField ftfModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTextArea taDireccion;
    private javax.swing.JTextField tfApelpM;
    private javax.swing.JTextField tfApelpT;
    private javax.swing.JTextField tfApelsM;
    private javax.swing.JTextField tfApelsT;
    private javax.swing.JTextField tfNombreM;
    private javax.swing.JTextField tfNombreT;
    private javax.swing.JTextField tfTelf1;
    private javax.swing.JTextField tfTelf2;
    private javax.swing.JTextField tfTelf3;
    private javax.swing.JTextField tfTelf4;
    // End of variables declaration//GEN-END:variables
}
