/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistadirecciones;

import controldirecciones.Control;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import umldirecciones.Provincia;

/**
 *
 * @author javi
 */
public class Formulario extends javax.swing.JDialog {

    public SeleccionMuni   seleccMuni;
    public SeleccionLoca   seleccLoca;
    public SeleccionCalle  seleccCalle;
    
    /**
     * Creates new form Formulario2
     * 
     * Nota: Se modifica el constructor, el tipo del padre pasa a ser "javax.swing.JDialog"
     *          para que pueda recibir como padre a un JDialog en vez de un JFrame.
     * 
     */
    public Formulario(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();this.setLocationRelativeTo(null);
        this.setAutoRequestFocus(rootPaneCheckingEnabled);
        this.tfLocalidad.setEnabled(false);
        this.bBuscarLoc.setEnabled(false);
        this.tfMunicipio.setEnabled(false);
        this.bBuscarMun.setEnabled(false);
        this.ftfCP.setEnabled(false);
        this.tfCalle.setEnabled(false);
        this.bBuscarCalle.setEnabled(false);
        this.tfPortal.setEnabled(false);
        this.tfPiso.setEnabled(false);
        this.tfEscalera.setEnabled(false);
        this.tfMano.setEnabled(false);
        this.bAceptar.setEnabled(false);
    }
    
    public void setLocalidad(String loc)
    {
        this.tfLocalidad.setText(loc);
    }

     
    public void setProvincias(ArrayList<Provincia> listado)
    {
        this.cbProvincia.addItem(" ");
        for (int i = 0; i < listado.size(); i++)
        {
            this.cbProvincia.addItem(listado.get(i).getNpro());          
        }
        
    }
    
    public void continuaLocalidades()
    {
        this.seleccMuni.dispose();
        this.tfMunicipio.setText(Control.direccion.getMunicipio().getNmun());
        this.tfMunicipio.setEnabled(false);
        this.bBuscarMun.setEnabled(false);
        this.tfLocalidad.setEnabled(true);
        this.bBuscarLoc.setEnabled(true);
    }
    
    public void continuaCalles()
    {
        this.seleccLoca.dispose();
        this.tfLocalidad.setText(Control.direccion.getLocalidad().getNentsi50());
        this.tfLocalidad.setEnabled(false);
        this.bBuscarLoc.setEnabled(false);
        this.ftfCP.setEnabled(true);
        this.tfCalle.setEnabled(true);
        this.bBuscarCalle.setEnabled(true);
    }
    
    public void continuaPortal()
    {
        this.seleccCalle.dispose();
        this.tfCalle.setText(Control.direccion.getVia().getTvia() + " " + Control.direccion.getVia().getNvia());
        this.tfCalle.setEnabled(false);
        this.bBuscarCalle.setEnabled(false);
        Control.direccion.setCp(Integer.parseInt(this.ftfCP.getText()));
        this.ftfCP.setEnabled(false);
        this.tfPortal.setEnabled(true);
        this.tfPiso.setEnabled(true);
        this.tfEscalera.setEnabled(true);
        this.tfMano.setEnabled(true);
        this.bAceptar.setEnabled(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bBuscarMun = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfPiso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfEscalera = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfMano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bSalir = new javax.swing.JButton();
        tfLocalidad = new javax.swing.JTextField();
        tfCalle = new javax.swing.JTextField();
        bBuscarLoc = new javax.swing.JButton();
        bBuscarCalle = new javax.swing.JButton();
        bElejirProv = new javax.swing.JButton();
        cbProvincia = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftfCP = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPortal = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfMunicipio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bBuscarMun.setText("Buscar");
        bBuscarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarMunActionPerformed(evt);
            }
        });

        jLabel10.setText("Piso");

        jLabel11.setText("Escalera");

        jLabel12.setText("Mano");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel8.setText("s/n = 0");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("DIRECCIÓN");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bBuscarLoc.setText("Buscar");
        bBuscarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarLocActionPerformed(evt);
            }
        });

        bBuscarCalle.setText("Buscar");
        bBuscarCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarCalleActionPerformed(evt);
            }
        });

        bElejirProv.setText("Elejir");
        bElejirProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bElejirProvActionPerformed(evt);
            }
        });

        jLabel1.setText("Provincia *");

        jLabel2.setText("Localidad *");

        jLabel3.setText("Calle *");

        jLabel4.setText("Código Postal *");

        try {
            ftfCP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Portal");

        jLabel9.setText("Municipio *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bElejirProv))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfMano, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ftfCP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bBuscarCalle))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tfMunicipio)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(bBuscarMun))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(bBuscarLoc)))))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bAceptar)
                                    .addGap(18, 18, 18)
                                    .addComponent(bSalir))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel7)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bElejirProv)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarMun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarLoc))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarCalle))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPortal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(49, 49, 49)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarMunActionPerformed
        seleccMuni = new SeleccionMuni(this, true);
        seleccMuni.cargaMunicipios(Control.buscaMunicipios(this.tfMunicipio.getText()));
        seleccMuni.setLocationRelativeTo(this);
        seleccMuni.setVisible(true);
    }//GEN-LAST:event_bBuscarMunActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        
        if(this.tfPortal.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "No has introducido el número de portal");
        else
        {
            Control.direccion.setTramo(
                Control.buscaTramo(Integer.parseInt(this.tfPortal.getText()), Integer.parseInt(this.ftfCP.getText()))
            );
            
            /* Este cacho de codigo se usa para comprobar que todos los datos que tiene direccion
            JOptionPane.showMessageDialog(this,
                "******************************************************\n"+
                "** LA DIRECCIÓN INTRODUCIDA ES CORRECTA **\n"+
                "******************************************************\n"+
                "******   los datos han sido comprobados   ******\n"+
                "******************************************************\n\n"+
                Control.direccion.toString()
            );
            */
        }
        this.dispose();
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBuscarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarLocActionPerformed
        seleccLoca = new SeleccionLoca(this, true);
        seleccLoca.cargaLocalidades(Control.buscaLocalidades(this.tfLocalidad.getText()));
        seleccLoca.setLocationRelativeTo(this);
        seleccLoca.setVisible(true);
    }//GEN-LAST:event_bBuscarLocActionPerformed

    private void bBuscarCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarCalleActionPerformed
        if(this.ftfCP.getValue()!=null)
        {
            seleccCalle = new SeleccionCalle(this, true);
            seleccCalle.cargaCalles(Control.buscaVias(this.tfCalle.getText()));
            seleccCalle.setLocationRelativeTo(this);
            seleccCalle.setVisible(true);
        }else
        JOptionPane.showMessageDialog(this, "No has introducido el código postal");
    }//GEN-LAST:event_bBuscarCalleActionPerformed

    private void bElejirProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElejirProvActionPerformed
        if (this.cbProvincia.getSelectedIndex()!=0)
        {
            this.cbProvincia.setEnabled(false);
            this.bElejirProv.setEnabled(false);
            Control.setProvinciaElegida(this.cbProvincia.getSelectedIndex()-1);
            this.tfMunicipio.setEnabled(true);
            this.bBuscarMun.setEnabled(true);
        }else
        JOptionPane.showMessageDialog(null, "No has elegido tu provincia!");

    }//GEN-LAST:event_bElejirProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBuscarCalle;
    private javax.swing.JButton bBuscarLoc;
    private javax.swing.JButton bBuscarMun;
    private javax.swing.JButton bElejirProv;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox cbProvincia;
    private javax.swing.JFormattedTextField ftfCP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tfCalle;
    private javax.swing.JTextField tfEscalera;
    private javax.swing.JTextField tfLocalidad;
    private javax.swing.JTextField tfMano;
    private javax.swing.JTextField tfMunicipio;
    private javax.swing.JTextField tfPiso;
    private javax.swing.JFormattedTextField tfPortal;
    // End of variables declaration//GEN-END:variables
}
